version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: mysql_sd_go
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root1234
    ports:
      - "33306:3006"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - sd_backend_network

  redis:
    image: redis:7.0
    container_name: redis_container
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    networks:
      - sd_backend_network

  crm.sd.com:
    container_name: crm_sd_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8008:8008"
    networks:
      - sd_backend_network
    depends_on:
      - mysql
      - redis
      
volumes:
  mysql_data:
  redis_data:

networks:
  sd_backend_network:
