server:
  port: 8008
  mode: "dev"
mysql: 
  host: mysql_container #127.0.0.1
  port: 3306 #33306
  username: root
  password: root1234
  dbName: mysql_sd_go
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  logLevel: debug
  fileLogName: "./storages/logs/dev.002.log"
  maxSize: 500
  maxBackups: 3
  maxAge: 28
  compress: true
redis:
  host: redis_container #127.0.0.1
  port: 6379 #6381
  password: 
  db: 0
  poolSize: 10